services:
  mysql-db:
    image: mysql:8.0
    container_name: pmanager-mysql
    restart: always
    environment:
      MYSQL_DATABASE: pmanager_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 10

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: pmanager-rabbit
    restart: always
    ports:
      - "5672:5672"   # Porta do protocolo AMQP
      - "15672:15672" # Porta do Painel de Controle
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  api-service:
    build: .
    container_name: pmanager-api
    ports:
      - "8080:8080"
    depends_on:
      mysql-db:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/pmanager_db?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_RABBITMQ_HOST=rabbitmq